#location: /crates/bot_core/Cargo.toml
[package]
name = "bot_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "bot_core"

[dependencies]
rust_decimal = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
rust_decimal_macros = "1"
serde_json = { workspace = true }
